@echo off
echo Creating virtual environment...
python -m venv .venv
echo Activating virtual environment...
call .venv\Scripts\activate
echo Upgrading pip...
python -m pip install --upgrade pip
echo Installing dependencies from requirements.txt...
pip install -r requirements.txt
echo Creating .env file...
echo GEMINI_API_KEY=__PUT_YOUR_KEY_HERE__> .env
echo.
echo Setup complete. Please edit the .env file and add your GEMINI_API_KEY.
pause
